## K-Fold Cross Validation

KFold divides the samples into k groups (folds) of approximately equal sizes. Out of these k groups, k-1 folds are used for training and the remaning one is used for testing.
This process is repeated k times 

##### KFold(n_splits=5, *, shuffle=False, random_state=None)

n_splits --> number of folds, default=5
shuffle: bool, default=False
Shuffle is used to shuffle the data before splitting it into batches. Samples within each split will not be shuffled.

random_state --> int, default=None
This is used to control the randomness of each fold and it affects the ordering of indices only when shuffle=True, else it doesn't have any effect

In [1]:
import numpy as np
from sklearn.model_selection import KFold
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [2]:
X = ["a",'b','c','d','e','f']
kf = KFold(n_splits=3,shuffle=False,random_state=None)


In [3]:
print(kf)

KFold(n_splits=3, random_state=None, shuffle=False)


In [4]:
#i=0
for train, test in kf.split(X):
    #print("Iteration:",i)
    print("Train:",train,"Test:",test)


Train: [2 3 4 5] Test: [0 1]
Train: [0 1 4 5] Test: [2 3]
Train: [0 1 2 3] Test: [4 5]


## Stratified K-Fold 

This technique is a variation of K-Fold, and it divides the data into k-stratified folds.
This way it preserves the percentage of samples of each class present in the data
* It generates test sets such that all sets contain the same distribution of classes, or as close as possible

##### sklearn.model_selection.StratifiedKFold(n_splits=5, *, shuffle=False, random_state=None)


In [5]:
from sklearn.model_selection import StratifiedKFold

In [6]:
X = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
y= np.array([0,0,1,0,1,1])
skf = StratifiedKFold(n_splits=3,random_state=None,shuffle=False)

for train_index,test_index in skf.split(X,y):
    print("Train:",train_index,'Test:',test_index)
    X_train,X_test = X[train_index], X[test_index]
    y_train,y_test = y[train_index], y[test_index]


Train: [1 3 4 5] Test: [0 2]
Train: [0 2 3 5] Test: [1 4]
Train: [0 1 2 4] Test: [3 5]


## Leave One Out Cross Validation
This is a simple technique in which training data inlcudes all observations in the data except one observation which will be used to test.

For n samples, we have n different training sets. 

Although this model is trained on almost all of the data, the number of iterations and n different training sets, makes it computationally very expensive.

Almost all of the data (n-1 of the n samples) is used to build each model, all of the models are identical to each other and this results in high variance compared KFold.

##### sklearn.model_selection import LeaveOneOut( )


In [7]:
from sklearn.model_selection import LeaveOneOut

In [8]:
X = [10,20,30,40,50,60,70,80,90,100]
l = LeaveOneOut()

for train, test in l.split(X):
    print("%s %s"% (train,test))

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


It is suggested that 5 or 10-Fold Cross Validation should be preferred over LOOCV

## Hold Out Cross Validation
Here  we split the data into 2 sets - train and test set. The split (either 70:30 or 80:20 or even 60:40) is totally dependent on the use case we are working on.

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X = [10,20,30,40,50,60,70,80,90,100]

train, test= train_test_split(X,test_size=0.3, random_state=1)
print("Train:",X_train,"Test:" ,X_test)

Train: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]] Test: [[ 7  8]
 [11 12]]


### Evaluating Cross validation methods on Cancer data

* Here I am trying to implement the different Cross Validation methods to check their accuracy on Cancer data

* I am not performing any EDA / Feature engineering as my goal is to implement Cross Validation models and check their accuracy

* Build a Decision tree to fit cancer data and perform cross validation

### Description about data

Link to data in kaggle : https://www.kaggle.com/uciml/breast-cancer-wisconsin-data



Features are computed from a digitized image of a fine needle aspirate (FNA) of a breast mass. They describe characteristics of the cell nuclei present in the image.
n the 3-dimensional space is that described in: [K. P. Bennett and O. L. Mangasarian: "Robust Linear Programming Discrimination of Two Linearly Inseparable Sets", Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server:
ftp ftp.cs.wisc.edu
cd math-prog/cpo-dataset/machine-learn/WDBC/

Also can be found on UCI Machine Learning Repository: https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29

Attribute Information:

1) ID number
2) Diagnosis (M = malignant, B = benign)
3-32)

Ten real-valued features are computed for each cell nucleus:

a) radius (mean of distances from center to points on the perimeter)
b) texture (standard deviation of gray-scale values)
c) perimeter
d) area
e) smoothness (local variation in radius lengths)
f) compactness (perimeter^2 / area - 1.0)
g) concavity (severity of concave portions of the contour)
h) concave points (number of concave portions of the contour)
i) symmetry
j) fractal dimension ("coastline approximation" - 1)

The mean, standard error and "worst" or largest (mean of the three
largest values) of these features were computed for each image,
resulting in 30 features. For instance, field 3 is Mean Radius, field
13 is Radius SE, field 23 is Worst Radius.

All feature values are recoded with four significant digits.

Missing attribute values: none

Class distribution: 357 benign, 212 malignant

In [11]:
data = pd.read_csv('E:\Learn\Data Science\Breast cancer prediction\data.csv')

In [12]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [13]:
data.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [14]:
data = data.drop(['Unnamed: 32'], axis=1)

Id feature will not be of any use for our model.

So I will drop it.

The data doesn't have any null values.

I will go ahead with model building without doing any exploratory data analysis as this is a widely used data.

And our purpose is to evaluate different cross validation techniques on the model

Our aim is to predict the severity of cancer based on the input features.

So we can use Decision trees to solve this classification problem

In [15]:
data['diagnosis'].nunique()

2

In [16]:
data['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [17]:
X = data.drop(['id','diagnosis'], axis=1)
y = data['diagnosis']

#### Hold One Out Method

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

In [20]:
dt = DecisionTreeClassifier()

In [21]:
dtmodel = dt.fit(X_train,y_train)

In [22]:
dt.score(X_train,y_train)

1.0

In [23]:
hoo_result = dtmodel.score(X_test,y_test)

In [24]:
print("The accuracy score is for Hold one out method :",hoo_result)

The accuracy score is for Hold one out method : 0.935672514619883


#### K-Fold Method

In [25]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import accuracy_score

In [26]:
dt = DecisionTreeClassifier()

In [27]:
kf= KFold(n_splits=5)

In [28]:
kfold_score = cross_val_score(dt,X,y,cv=kf)

In [29]:
print("The cross validation scores of k-fold method with 5 folds is",kfold_score)

The cross validation scores of k-fold method with 5 folds is [0.86842105 0.92982456 0.93859649 0.9122807  0.87610619]


In [30]:
kfold_score_mean = kfold_score.mean()

In [31]:
print("The min accuracy from k-fold CV is",min(kfold_score))
print("The max accuracy from k-fold CV is", max(kfold_score))
print("The mean cross validation scores of k-fold method with 5 folds is",kfold_score_mean)

The min accuracy from k-fold CV is 0.868421052631579
The max accuracy from k-fold CV is 0.9385964912280702
The mean cross validation scores of k-fold method with 5 folds is 0.9050458003415619


#### complete implementation of k-fold cross validation

In [32]:
kf2=KFold(n_splits=5)
acc_score_kfold = []


In [33]:
for train_ind,test_ind in kf2.split(X,y):
    #print("Train:",train_ind,'Test:',test_ind)
    X_train,X_test = X.iloc[train_ind,:], X.iloc[test_ind,:]
    y_train,y_test = y[train_ind], y[test_ind]
    
    dt.fit(X_train,y_train)
    pred_values = dt.predict(X_test)
     
    acc = accuracy_score(pred_values , y_test)
    acc_score_kfold.append(acc)
     
avg_acc_score = sum(acc_score_kfold)/5
 
print('accuracy of each fold : {}'.format(acc_score_kfold))
print('Avg accuracy : {}'.format(avg_acc_score))


accuracy of each fold : [0.8596491228070176, 0.8947368421052632, 0.9385964912280702, 0.9298245614035088, 0.8584070796460177]
Avg accuracy : 0.8962428194379755


## Stratified K-Fold method


In [34]:
from sklearn.model_selection import StratifiedKFold

In [35]:
skfold = StratifiedKFold(n_splits=10)

In [36]:
skfold_score = cross_val_score(dt,X,y,cv=skfold)

In [37]:
print("The accuracy of Stratified k-fold method with 10 folds is",skfold_score)

The accuracy of Stratified k-fold method with 10 folds is [0.92982456 0.87719298 0.9122807  0.89473684 0.96491228 0.89473684
 0.85964912 0.94736842 0.92982456 0.96428571]


In [38]:
skfold_score_mean = skfold_score.mean()
print("The accuracy of Stratifieid k-fold method with 10 folds is",skfold_score_mean)

The accuracy of Stratifieid k-fold method with 10 folds is 0.9174812030075186


### Leave One Out Method

In [39]:
from sklearn.model_selection import LeaveOneOut

In [40]:
loocv = LeaveOneOut()

In [41]:
loocv_score = cross_val_score(dt,X,y,cv=loocv)

In [42]:
print("The accuracy of Leave one out method is",loocv_score)

The accuracy of Leave one out method is [1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1

In [43]:
loocv_score_mean = loocv_score.mean()
print("The average accuracy of Leave one out method with is",loocv_score_mean)

The average accuracy of Leave one out method with is 0.9244288224956063
